# ===================================================================
# Spring Boot configuration for the "secret-samples" profile.
#
# This configuration overrides the application.yml file.
#
# More information on profiles: https://www.jhipster.tech/profiles/
# More information on configuration properties: https://www.jhipster.tech/common-application-properties/
# ===================================================================

# ===================================================================
# Samples for required secrets to be used in development and ci using prod profile.
# ===================================================================

spring:

jhipster:
  security:
    authentication:
      jwt:
        base64-secret: YjE4NGQ3Mjg5ODU5Nzg3OTA3YmExYzZlMmZhYzlmOTcyMzdmOGE1NmVjZmMxNGMwYzNiMTg5YzNmYjQ4NDcyNDY2MzYxYTFiNGI2Yjk4YWFmOTg3Nzg1MmQ3MjliNTY4ZWVjZjFkZTNlMWU2MTJjY2UwYThmNmMyZThiZDkwNTY=
---
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    username: blueSky
    password:
---
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    username: root
    password:
