export enum AircraftCategory {
  PISTON_SINGLE = 'PISTON_SINGLE',

  TURBOPROP = 'TURBOPROP',

  REGIONAL_JET = 'REGIONAL_JET',

  NARROWBODY_JET = 'NARROWBODY_JET',

  WIDEBODY_JET = 'WIDEBODY_JET',
}
