package com.bluesky.simulations.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class AchievementAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAchievementAllPropertiesEquals(Achievement expected, Achievement actual) {
        assertAchievementAutoGeneratedPropertiesEquals(expected, actual);
        assertAchievementAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAchievementAllUpdatablePropertiesEquals(Achievement expected, Achievement actual) {
        assertAchievementUpdatableFieldsEquals(expected, actual);
        assertAchievementUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAchievementAutoGeneratedPropertiesEquals(Achievement expected, Achievement actual) {
        assertThat(actual)
            .as("Verify Achievement auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAchievementUpdatableFieldsEquals(Achievement expected, Achievement actual) {
        assertThat(actual)
            .as("Verify Achievement relevant properties")
            .satisfies(a -> assertThat(a.getCode()).as("check code").isEqualTo(expected.getCode()))
            .satisfies(a -> assertThat(a.getTitle()).as("check title").isEqualTo(expected.getTitle()))
            .satisfies(a -> assertThat(a.getDescription()).as("check description").isEqualTo(expected.getDescription()))
            .satisfies(a -> assertThat(a.getBadgeIcon()).as("check badgeIcon").isEqualTo(expected.getBadgeIcon()))
            .satisfies(a -> assertThat(a.getXpReward()).as("check xpReward").isEqualTo(expected.getXpReward()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAchievementUpdatableRelationshipsEquals(Achievement expected, Achievement actual) {
        assertThat(actual)
            .as("Verify Achievement relationships")
            .satisfies(a -> assertThat(a.getPilotses()).as("check pilotses").isEqualTo(expected.getPilotses()));
    }
}
