package com.bluesky.simulations.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class AircraftAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAircraftAllPropertiesEquals(Aircraft expected, Aircraft actual) {
        assertAircraftAutoGeneratedPropertiesEquals(expected, actual);
        assertAircraftAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAircraftAllUpdatablePropertiesEquals(Aircraft expected, Aircraft actual) {
        assertAircraftUpdatableFieldsEquals(expected, actual);
        assertAircraftUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAircraftAutoGeneratedPropertiesEquals(Aircraft expected, Aircraft actual) {
        assertThat(actual)
            .as("Verify Aircraft auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAircraftUpdatableFieldsEquals(Aircraft expected, Aircraft actual) {
        assertThat(actual)
            .as("Verify Aircraft relevant properties")
            .satisfies(a -> assertThat(a.getTailNumber()).as("check tailNumber").isEqualTo(expected.getTailNumber()))
            .satisfies(a -> assertThat(a.getModelName()).as("check modelName").isEqualTo(expected.getModelName()))
            .satisfies(a -> assertThat(a.getIcaoType()).as("check icaoType").isEqualTo(expected.getIcaoType()))
            .satisfies(a -> assertThat(a.getCategory()).as("check category").isEqualTo(expected.getCategory()))
            .satisfies(a -> assertThat(a.getCruiseSpeedKnots()).as("check cruiseSpeedKnots").isEqualTo(expected.getCruiseSpeedKnots()))
            .satisfies(a -> assertThat(a.getMaxRangeNm()).as("check maxRangeNm").isEqualTo(expected.getMaxRangeNm()))
            .satisfies(a -> assertThat(a.getServiceCeilingFt()).as("check serviceCeilingFt").isEqualTo(expected.getServiceCeilingFt()))
            .satisfies(a -> assertThat(a.getFuelBurnGph()).as("check fuelBurnGph").isEqualTo(expected.getFuelBurnGph()))
            .satisfies(a -> assertThat(a.getMinRunwayLengthFt()).as("check minRunwayLengthFt").isEqualTo(expected.getMinRunwayLengthFt()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAircraftUpdatableRelationshipsEquals(Aircraft expected, Aircraft actual) {
        // empty method
    }
}
