package com.bluesky.simulations.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class AirportAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAirportAllPropertiesEquals(Airport expected, Airport actual) {
        assertAirportAutoGeneratedPropertiesEquals(expected, actual);
        assertAirportAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAirportAllUpdatablePropertiesEquals(Airport expected, Airport actual) {
        assertAirportUpdatableFieldsEquals(expected, actual);
        assertAirportUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAirportAutoGeneratedPropertiesEquals(Airport expected, Airport actual) {
        assertThat(actual)
            .as("Verify Airport auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAirportUpdatableFieldsEquals(Airport expected, Airport actual) {
        assertThat(actual)
            .as("Verify Airport relevant properties")
            .satisfies(a -> assertThat(a.getIcaoCode()).as("check icaoCode").isEqualTo(expected.getIcaoCode()))
            .satisfies(a -> assertThat(a.getIataCode()).as("check iataCode").isEqualTo(expected.getIataCode()))
            .satisfies(a -> assertThat(a.getName()).as("check name").isEqualTo(expected.getName()))
            .satisfies(a -> assertThat(a.getCity()).as("check city").isEqualTo(expected.getCity()))
            .satisfies(a -> assertThat(a.getCountry()).as("check country").isEqualTo(expected.getCountry()))
            .satisfies(a -> assertThat(a.getLatitude()).as("check latitude").isEqualTo(expected.getLatitude()))
            .satisfies(a -> assertThat(a.getLongitude()).as("check longitude").isEqualTo(expected.getLongitude()))
            .satisfies(a -> assertThat(a.getElevationFt()).as("check elevationFt").isEqualTo(expected.getElevationFt()))
            .satisfies(a -> assertThat(a.getLongestRunwayFt()).as("check longestRunwayFt").isEqualTo(expected.getLongestRunwayFt()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAirportUpdatableRelationshipsEquals(Airport expected, Airport actual) {
        // empty method
    }
}
