package com.bluesky.simulations.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class FlightLogAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFlightLogAllPropertiesEquals(FlightLog expected, FlightLog actual) {
        assertFlightLogAutoGeneratedPropertiesEquals(expected, actual);
        assertFlightLogAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFlightLogAllUpdatablePropertiesEquals(FlightLog expected, FlightLog actual) {
        assertFlightLogUpdatableFieldsEquals(expected, actual);
        assertFlightLogUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFlightLogAutoGeneratedPropertiesEquals(FlightLog expected, FlightLog actual) {
        assertThat(actual)
            .as("Verify FlightLog auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFlightLogUpdatableFieldsEquals(FlightLog expected, FlightLog actual) {
        assertThat(actual)
            .as("Verify FlightLog relevant properties")
            .satisfies(a -> assertThat(a.getDepartureTime()).as("check departureTime").isEqualTo(expected.getDepartureTime()))
            .satisfies(a -> assertThat(a.getArrivalTime()).as("check arrivalTime").isEqualTo(expected.getArrivalTime()))
            .satisfies(a -> assertThat(a.getDurationHours()).as("check durationHours").isEqualTo(expected.getDurationHours()))
            .satisfies(a -> assertThat(a.getDistanceNm()).as("check distanceNm").isEqualTo(expected.getDistanceNm()))
            .satisfies(a -> assertThat(a.getCruiseAltitudeFt()).as("check cruiseAltitudeFt").isEqualTo(expected.getCruiseAltitudeFt()))
            .satisfies(a -> assertThat(a.getFuelUsedGallons()).as("check fuelUsedGallons").isEqualTo(expected.getFuelUsedGallons()))
            .satisfies(a -> assertThat(a.getXpEarned()).as("check xpEarned").isEqualTo(expected.getXpEarned()))
            .satisfies(a -> assertThat(a.getFlightRules()).as("check flightRules").isEqualTo(expected.getFlightRules()))
            .satisfies(a -> assertThat(a.getRemarks()).as("check remarks").isEqualTo(expected.getRemarks()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFlightLogUpdatableRelationshipsEquals(FlightLog expected, FlightLog actual) {
        assertThat(actual)
            .as("Verify FlightLog relationships")
            .satisfies(a -> assertThat(a.getAircraft()).as("check aircraft").isEqualTo(expected.getAircraft()))
            .satisfies(a -> assertThat(a.getDepartureAirport()).as("check departureAirport").isEqualTo(expected.getDepartureAirport()))
            .satisfies(a -> assertThat(a.getArrivalAirport()).as("check arrivalAirport").isEqualTo(expected.getArrivalAirport()))
            .satisfies(a -> assertThat(a.getPilot()).as("check pilot").isEqualTo(expected.getPilot()));
    }
}
