package com.bluesky.simulations.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class PilotProfileAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPilotProfileAllPropertiesEquals(PilotProfile expected, PilotProfile actual) {
        assertPilotProfileAutoGeneratedPropertiesEquals(expected, actual);
        assertPilotProfileAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPilotProfileAllUpdatablePropertiesEquals(PilotProfile expected, PilotProfile actual) {
        assertPilotProfileUpdatableFieldsEquals(expected, actual);
        assertPilotProfileUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPilotProfileAutoGeneratedPropertiesEquals(PilotProfile expected, PilotProfile actual) {
        assertThat(actual)
            .as("Verify PilotProfile auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPilotProfileUpdatableFieldsEquals(PilotProfile expected, PilotProfile actual) {
        assertThat(actual)
            .as("Verify PilotProfile relevant properties")
            .satisfies(a -> assertThat(a.getTotalXp()).as("check totalXp").isEqualTo(expected.getTotalXp()))
            .satisfies(a -> assertThat(a.getRankTier()).as("check rankTier").isEqualTo(expected.getRankTier()))
            .satisfies(a -> assertThat(a.getTotalFlightHours()).as("check totalFlightHours").isEqualTo(expected.getTotalFlightHours()))
            .satisfies(a ->
                assertThat(a.getTotalNightFlightHours()).as("check totalNightFlightHours").isEqualTo(expected.getTotalNightFlightHours())
            )
            .satisfies(a ->
                assertThat(a.getTotalIfrFlightHours()).as("check totalIfrFlightHours").isEqualTo(expected.getTotalIfrFlightHours())
            )
            .satisfies(a -> assertThat(a.getFlightsCompleted()).as("check flightsCompleted").isEqualTo(expected.getFlightsCompleted()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPilotProfileUpdatableRelationshipsEquals(PilotProfile expected, PilotProfile actual) {
        assertThat(actual)
            .as("Verify PilotProfile relationships")
            .satisfies(a -> assertThat(a.getAchievements()).as("check achievementses").isEqualTo(expected.getAchievements()));
    }
}
